### ISSUE TITLE
Recurring events do not set the slack status

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2slackstatus#1]
I assume this is due to how they are stored in the ical.

**Comment by pauldeden** [comment]
For example, the weekly meeting with title "Release Change Advisory Board" doesn't set my status.

**Comment by ndpete** [comment]
Yeah it looks like recurring appointments don't spawn new events each day. I'll have to dig in to the ical file and figure out some logic to try and include them.

**Comment by pauldeden** [comment]
The bug fix has a bug :slightly_smiling_face:.  I have a recurring event on my calendar for now and just tried it and got the following `[ERROR]    2017-08-10T19:16:24.933Z    5e6b762c-7e00-11e7-ba28-8f783f4419f1    Exception raised while trying to set pde2's status.  Exeption was TypeError("can't compare offset-naive and offset-aware datetimes",)` (edited)
