### ISSUE TITLE
Multiple errors for some users this morning

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2slackstatus#12]
Here's what's in the logs.  

![screenshot 2017-08-28 at 8 10 21 am](https://user-images.githubusercontent.com/4304479/29777238-81503714-8bc8-11e7-998b-5ea549892013.png)

@ndpete can you look into this today?

**Comment by ndpete** [comment]
This issue with status was that I inadvertently uploaded the wrong config yml to the wrong bucket. That has been resolved.

The issue with yours is a larger bug that apparently all day events aren't parsing correctly. I'm working to identify what is going on there. 

The putitem errors looks like an event or something with an empty string. I'll add some logic to avoid that.

**Comment by ndpete** [comment]
These should all be resolved by this commit 6b568bfd6de267a44a5776db5cd5e256037f2906
