### ISSUE TITLE
Slack user when they specify an invalid emoji

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2slackstatus#13]
Today, when a user specifies an invalid emoji on one of their ical events the following is entered in the cloudwatch log for the lambda function
```
[ERROR]	2017-08-29T15:15:56.173Z	e926f1d5-8ccc-11e7-ba22-0bb3c6c657c7	Error setting pde2's status. Details are: {'ok': False, 'error': 'profile_status_set_failed_not_valid_emoji'}
```

The downside of this is the user doesn't know they need to do anything about the problem or even know there is a problem aside from their slack status not being set.

Better would be to slack the user whenever they have an invalid emoji indicating in the slack message what event has the invalid emoji so they know what to fix.

**Comment by pauldeden** [comment]
The event name that caused the error above was `Resting to get over a cold :face_with_thermometer:`.  The correct emoji name is 🤒

**Comment by ndpete** [comment]
@pauldeden How should we handle the ability to post the slack message? Have users add the post message permission to there app and just use the API or use an incoming webhook? if we use a webhook. Is there a generic incoming webhook we can use or will we need to create a new one.

**Comment by ndpete** [comment]
Looks like regardless of which option we take we will have to add logic to make calls to the CMDB as I can't find an easy way to identify the user of token being used. Easiest looks like calling the cmdb to get the slack username based on net_id

**Comment by pauldeden** [comment]
True. And we can use an incoming web hook to slack any user.

**Comment by pauldeden** [comment]
The codebuild portion of the codepipeline failed with the following error.

<img width="1011" alt="screen shot 2017-08-31 at 1 42 11 pm" src="https://user-images.githubusercontent.com/4304479/29942203-4c0c4778-8e52-11e7-838b-b9cbf3871262.png">

**Comment by ndpete** [comment]
Sorry this looks like an oversight on my part let me rework the requirements files so they are correct between codebuild and app deployment.

**Comment by ndpete** [comment]
This is resolved now.
