### ISSUE TITLE
Smart handling of manually set statuses

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2slackstatus#5]
@saholman said, "You could probably keep track of the last status that was pushed to slack and if the current status is different, and was changed within the last hour or so then don’t change it."

We would need to setup some type of persistence (s3 or Dynamo likely) to save the last status set by ical2slackstatus for each person with a yml file in the bucket.

**Comment by joshgubler** [comment]
Example:
ical sets the status to 'a'
user sets the status to 'b'
ical sees that it is trying to set the status back to 'a' so it doesn't
eventually, ical sets the status to 'c'

This would also have the advantage of only making api calls to slack.set_status when necessary.

So to summarize: Only set the status if it is different from what you set it to last time. Don't worry about checking the status in slack. It doesn't matter. Just compare 'new ical status' with 'last new ical status'.
