### ISSUE TITLE
Not ignoring cancelled appointments

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/ical2slackstatus#9]
It's a frequent enough occurrence that meetings are cancelled.  Today, those meetings are still used for setting slack status.  We need to ignore them so that a more accurate slack status can be used.

**Comment by pauldeden** [comment]
Here are two screenshots from just now that show my calendar and a denied instance of a repeating appointment showing up as my slack status when it shouldn't.

![screenshot 2017-08-21 at 12 16 13 pm](https://user-images.githubusercontent.com/4304479/29532623-296b7ce6-866b-11e7-85f9-bb19f02d9184.png)

![screenshot 2017-08-21 at 12 17 35 pm](https://user-images.githubusercontent.com/4304479/29532626-2e7f7a20-866b-11e7-9e95-17e827afc8bc.png)

**Comment by ndpete** [comment]
Raw output of the offending event from above:

```
[Event([('RRULE',
         vRecur([('FREQ', ['WEEKLY']),
                 ('UNTIL',
                  [datetime.datetime(2017, 11, 20, 19, 0, tzinfo=<UTC>)]),
                 ('INTERVAL', [1]),
                 ('BYDAY', ['MO']),
                 ('WKST', ['SU'])])),
        ('EXDATE', <icalendar.prop.vDDDLists at 0x10e3bbf60>),
        ('SUMMARY', vText('b'OIT Singers Weekly Get Together'')),
        ('DTSTART', <icalendar.prop.vDDDTypes at 0x10e3f3ef0>),
        ('DTEND', <icalendar.prop.vDDDTypes at 0x10e3bbef0>),
        ('UID',
         vText('b'040000008200E00074C5B7101A82E00800000000C0C0F46A6B9ED2010000000000000000100000003BAF31CCFB540248847621A2E6700DC8'')),
        ('CLASS', vText('b'PUBLIC'')),
        ('PRIORITY', 5),
        ('DTSTAMP', <icalendar.prop.vDDDTypes at 0x10e694908>),
        ('TRANSP', vText('b'OPAQUE'')),
        ('STATUS', vText('b'CONFIRMED'')),
        ('SEQUENCE', 4),
        ('LOCATION', vText('b'ITB 1006 (10-25 ppl)'')),
        ('X-MICROSOFT-CDO-APPT-SEQUENCE', vText('b'4'')),
        ('X-MICROSOFT-CDO-BUSYSTATUS', vText('b'BUSY'')),
        ('X-MICROSOFT-CDO-INTENDEDSTATUS', vText('b'BUSY'')),
        ('X-MICROSOFT-CDO-ALLDAYEVENT', vText('b'FALSE'')),
        ('X-MICROSOFT-CDO-IMPORTANCE', vText('b'1'')),
        ('X-MICROSOFT-CDO-INSTTYPE', vText('b'1'')),
        ('X-MICROSOFT-DISALLOW-COUNTER', vText('b'FALSE''))])]
```

Looks like the canceled event are handled different then all the cases I tried to test. In every case I tested the events would be removed. In this case it looks like the date is being add to exdate field. (Not sure yet how to reproduce this)
Which means we probably need to refactor the recurring stuff to be a recurring set to try and consume the exdate fields. Pull request coming.

**Comment by pauldeden** [comment]
Great work!  Thanks.
